[versions]
junit-bom = "5.13.1"
lombok-plugin = "8.13.1"
commons-lang = "3.17.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter"}
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
commons-lang = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang"}

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin" }
